version: '3'

volumes:
  mgdata:
  static_files:
  uploaded_files:

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    depends_on:
      - db
    links:
      - db:mongodbhost
    container_name: recsys_web_1
    restart: always
    
  db:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    expose:
      - "27017"
    # command: mongod --auth --bind_ip all
    # command: mongod --port 27017 --bind_ip 0.0.0.0
    volumes:
      - mgdata:/var/lib/mongodb/data/
    container_name: recsys_db_1
    restart: always
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      # nginx needs to access static files (readonly) and uploaded files(read+write)
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    depends_on:
      - web
    restart: always
