version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    links:
      - db:mongodb
    container_name: recsys_web_1
    restart: always
  db:
    image: mongo:4.0.4
    container_name: recsys_db_1
